import { Metadata } from "next";
import localFont from "next/font/local";
import React from "react";
import { AuthProvider } from "./_provider";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";
import { TanstackProvider } from "./_provider/tanstack";
import { CssBaseline, ThemeProvider } from "@mui/material";
import theme from "./_mui/theme";
import MuiProviders from "./_provider/mui";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Foody Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>Root header</div>
        <TanstackProvider>
          <AuthProvider>
            <MuiProviders>
              {children}
            </MuiProviders>
          </AuthProvider>
        </TanstackProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
